### ISSUE TITLE
Update Flutter Packages

### ISSUE THREAD

**Issue by edufolly** [lucashilles/flutter-dev-container#5]
Error:
```
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
```

Add in dockerfile:
```flutter update-packages```

**Comment by lucashilles** [comment]
Fixed with this [commit](https://github.com/lucashilles/flutter-dev-container/commit/afca971cfe11f4dad8a2f22fff7bab7a807e6987).
